#!/bin/bash
#####################
##     aliases     ##
##############################################################################
## Создать в среде окружении шелла функции-хелперы для работы с приложением ##
##############################################################################
: '
 
  a. Подключить конфиг CLI-приложения

  1. Включить expanding алиасов в скрипте
  2. Сообщить о начале назначения алиасов
  3. Определить алиасы
  4. Сообщить о конце назначения алиасов
 
'
#########################################################################

# 1. Включить expanding алиасов в скрипте
shopt -s expand_aliases

# 2. Сообщить о начале назначения алиасов
echo -e "$YELLOW Начинаю добавление алиасов в окрушение текущего шелла... $NORMAL"

# 3. Определить алиасы
echo "----------------------------"

  # 3.1. node
  alias node='function f(){   docker-compose run --rm --service-ports node node "$@";  };f'
  echo -e "$YELLOW -- node [docker-compose run --rm --service-ports node node "$@"] $NORMAL"
  
  # 3.2. npm
  alias npm='function f(){   docker-compose run --rm --service-ports node npm "$@";  };f'
  echo -e "$YELLOW -- npm [docker-compose run --rm --service-ports node npm "$@"] $NORMAL"
  
  # 3.3. gulp
  alias gulp='function f(){   docker-compose run --rm --service-ports node gulp "$@";  };f'
  echo -e "$YELLOW -- gulp [docker-compose run --rm --service-ports node gulp "$@"] $NORMAL"
  
  # 3.4. bower
  alias bower='function f(){   docker-compose run --rm --service-ports node bower --allow-root "$@";  };f'
  echo -e "$YELLOW -- bower [docker-compose run --rm --service-ports node bower --allow-root "$@"] $NORMAL"
  
  # 3.5. php
  alias php='function f(){   docker-compose run --rm --service-ports nginx php "$@";  };f'
  echo -e "$YELLOW -- php [docker-compose run --rm --service-ports nginx php "$@"] $NORMAL"
  
  # 3.6. artisan
  alias artisan='function f(){   docker-compose --rm --service-ports run nginx php artisan "$@"; };f'
  echo -e "$YELLOW -- artisan [docker-compose --rm --service-ports run nginx php artisan "$@"] $NORMAL"
  
  # 3.7. composer
  alias composer='function f(){   docker-compose --rm --service-ports run nginx composer "$@"; };f' 
  echo -e "$YELLOW -- composer [docker-compose --rm --service-ports run nginx composer "$@"] $NORMAL"
  
echo "----------------------------"  
  
# 4. Сообщить о конце назначения алиасов
echo -e "$GREEN Добавление алиасов успешно завершено! $NORMAL"