#!/bin/bash
#####################
##     install     ##
####################################################
## Произвести установку проекта в текущий каталог ##
####################################################
: '
 
  1. Если проект уже установлен, сообщить и завершить
  2. Произвести простановку путей в ряде файлов

    2.1. Записать в переменную текущий путь
    2.2. Проставить пути в docker-compose.yml
    2.3. Проставить пути в configs/groups/dev/nginx/sites/project.app 
    2.4. Проставить пути в configs/groups/dev/supervisor/supervisor.ini
    2.5. Проставить пути в configs/groups/dev/supervisor/websocket.ini 
 
  3. Произвести установку баз данных
  4. Сделать отметку в конфиге, что проект установлен

'
#########################################################################
func_wrapper_install () { 

  # 1. Если проект уже установлен, сообщить и завершить
  if [ $is_project_installed != 0 ]; then 

    # Сообщить
    echo "Проект уже установлен. Установить проект можно лишь 1-ин раз."

    # Завершить
    return

  fi

  # 2. Произвести простановку путей в ряде файлов

    # 2.1. Сообщить 
    echo "---> Произвожу подстановку пути к корню проекта в файлы проекта..."

    # 2.2. Записать в переменную текущий путь
    project_path=$PWD

    # 2.3. Проставить пути
    {
      :
      # 1] Проставить пути в docker-compose.yml
      sed -i -e "s#<path_to_the_project>#$project_path#g" docker-compose.yml

      # 2] Проставить пути в configs/groups/dev/nginx/sites/project.app
      sed -i -e "s#<path_to_the_project>#$project_path#g" configs/groups/dev/nginx/sites/project.app

      # 3] Проставить пути в configs/groups/dev/supervisor/supervisor.ini
      sed -i -e "s#<path_to_the_project>#$project_path#g" configs/groups/dev/supervisor/supervisor.ini

      # 4] Проставить пути в configs/groups/dev/supervisor/websocket.ini
      sed -i -e "s#<path_to_the_project>#$project_path#g" configs/groups/dev/supervisor/websocket.ini

    } || {
      echo "---> Ошибка! Cм.строку $LINENO скрипта $BASH_SOURCE"
      return
    }  

    # 2.4. Сообщить 
    echo "---> Успех!"

  # 3. Произвести установку баз данных
  # - Скопировать содержимое каталога data/install в каталог data
 
    # 3.1. Сообщить
    echo "---> Устанавливаю базы данных проекта..."

    # 3.2. Скопировать
    {
      sudo cp -rf data/install/* data/
    } || {
      echo "---> Ошибка! Cм.строку $LINENO скрипта $BASH_SOURCE"
      return
    }  

    # 3.3. Сообщить
    echo "---> Успех!"

  # 4. Сделать отметку в конфиге, что проект установлен
  
    # 4.1. Сделать отметку
    {

      # Сообщить
      echo "---> Делаю отметку в конфиге о том, что проект установлен..."

      # Сделать отметку
      sed -i -e "s#is_project_installed=0#is_project_installed=1#" other/cli/config

    } || {
      echo "---> Ошибка! Cм.строку $LINENO скрипта $BASH_SOURCE"
      return      
    }

    # 4.2. Сообщить
    echo "---> Успех!"

  # n. Сообщить об успешной установке проекта
  echo "---> Проект успешно установлен в каталог: '$project_path'"

:;}
func_wrapper_install "$@"



